---
###################################################
# This job can be used as a template to backup a database 
# into a ftp storage.
# Replace the values in brackets []
###################################################
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres2ftp-backup
  namespace: [YOUR NAMESPACE]
spec:
  template:
    spec:
      containers:
        - name: pgbackupk8s
          image: imixs/pgbackupk8s:latest
          env:
          - name: POSTGRES_HOST
            value: db
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: [YOUR DATABASE]
          - name: POSTGRES_USER
            value: [YOUR POSTGRES USER]
          - name: POSTGRES_PASSWORD
            value: [YOUR PASSWORD]
          - name: FTP_HOST
            value: "[YOUR FTP SERVER]"
          - name: FTP_USER
            value: "[YOUR FTP USER]"
          - name: SSH_KEY
            value: "/root/keys/backupspace_rsa" # the location of your ssh key file in a config map
          - name: BACKUP_ROOT_DIR
            value: "/"          
          - name: BACKUP_MAX_ROLLING
            value: "3"          

          # Run the backup script
          command: ["/root/backup.sh"]

          volumeMounts:
          - name: rsa-key
            mountPath: /root/keys
      volumes:
      - name: rsa-key
        configMap:
          name: rsa-key

      restartPolicy: Never
  backoffLimit: 1
